"""init

Revision ID: 00ffc3bbe273
Create Date: 2023-09-05 23:00:25.968836

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "00ffc3bbe273"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("type", sa.Enum("EMAIL", "SMS", "PUSH", name="tasktype"), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CREATED", "PROCESSING", "COMPLETED", "PART_COMPLETED", "ERROR", name="taskstatus"),
            nullable=True,
        ),
        sa.Column("send_to", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("CREATED", "PROCESSING", "COMPLETED", "ERROR", name="notificationstatus"), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    op.drop_table("task")
    # ### end Alembic commands ###
